/// Flutter icons CustomGymIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
// /    - family:  CustomGymIcons
// /      fonts:
// /       - asset: fonts/CustomGymIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomGymIcons {
  CustomGymIcons._();

  static const _kFontFam = 'CustomGymIcons';
  static const _kFontPkg = null;

  static const IconData barrels = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData boxing_gloves = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chest_expander = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chest_expander_1 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chest_expander_2 = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dumbbell = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dumbbell_1 = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dumbbell_2 = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dumbbell_3 = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dumbbell_4 = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dumbbell_5 = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dumbbell_6 = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dumbbell_7 = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dumbbell_8 = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dumbbells = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gym = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gym_gloves = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hand_grip = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData jumping_rope = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kettlebell = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kettlebells = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData machine = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData machine_1 = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData machine_2 = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData machine_3 = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData machine_4 = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData machine_5 = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData measuring_tape = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medicine_ball = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pull_up_bar = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pull_up_bar_1 = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData punching_bag = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData punching_ball = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rings = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stationary_bike = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stationary_bike_1 = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData step = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData treadmill = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData treadmill_1 = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData treadmill_2 = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trellis = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vaulting_horse = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData weight = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData weight_1 = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData weight_2 = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData weights = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData weights_1 = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData weights_2 = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData yoga_mat = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ball = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
